kube-prometheus-stack:
  grafana:
    adminPassword: admin
    additionalDataSources:
    - access: proxy
      isDefault: false
      name: Loki
      type: loki
      url: http://loki.default:3100
    dashboards:
      default:
        loki:
          gnetId: 13639
          revision: 2
          datasource:
            - name: DS_LOKI
              value: Loki