kube-prometheus-stack:
  grafana:
    adminPassword: admin
    additionalDataSources:
    - access: proxy
      isDefault: false
      name: Loki
      type: loki
      url: http://loki.default:3100
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        loki:
          gnetId: 13639
          revision: 2
          datasource:
            - name: DS_LOKI
              value: Loki