grafana:
  adminPassword: "admin"
  sidecar:
    dashboards:
      default:
        logs:
          gnetId: 13639
          datasource:
            - name: DS_LOKI
              value: Loki
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      basicAuth: false
      editable: false
      isDefault: false
      url: http://loki.default:3100