{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "postgres-secrets",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "postgres-secrets",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "password": "AgAOV9dh2kU3V/BTcQsszfinvXI+Brn8OpwODjn6EeEnHrB/rfPh8PFRQa5AVQVwkEa7OKZ3iGRIRuGXVAz2t3b8F6pUFcoLFjiJhsCxdkZXfsyqEYvmV0DCjnA6Cd1L0M1NUwcry0kK/mp/EyfbbpDvSiPbJMn6oX/aIsXvIgvCmEsua79PwbxCFKhoE4PcboE9Wj5foUVCoVMZVxNhunreqfLJGtAZO9mfIP5oM61RPUia3xg1sBMIAS92PgY5DOBbU46kIVoM+nKBENRpcScLU9r9d0yHWVYC7VcgCWb1LVCaxL7AUaXuQWQRlsQYzI/aP2AL/ZG/X4mcamy9VHOyBBRmdg8VqQ/FGug6zczxM/m3QIEewBvtn2Zge4mutCjeCjP6NzlOIKIemCKyGMWKs01miEdwAktkI53I82VQJxzyVzNyDbKSPYVPUW5bMVlmC2Yq/8RDfuJYkx7CTCNS+aRFrnj2yEMN67rqZUjbOrJqIkntaUGjoSPAJfyyLqtDZtc1BzFaqSSBag+gESAZK0+VYvGZUpYEbqKM6c02KCNU/hs9jdmqrMAsVvDsqv1ILWoTuIsdxkvpoK3oyICG53EZMG6b44k1r0D0EtO4PCZntCkGYVAxz6orcxs9asi342RvNuL0xaylN6/GchHL67XDT1fumaUCVFzRSLrbfvPJesGLm2LQtNKnMKEl17DLOmI20ZExGX0iHE0=",
      "postgres-password": "AgAAhaD0srqnqQlq69epd6mUq3CNmr6ck6aRh1ZbKujXVaJ4TKnEsr37uSr44PHJ7WmlxdAZjZ8o7vAuLfSMCDR+n3FG+OhyPiotSFyxPiq222o5+u+/3pictsFwzttkToUu2uFZmapHwSo4udXZQKc2zq92CQLNY0YdmMsifWS38yDC/l465ZV0WZw27TxR4OsbB1v5okIUW4nCAKpgHT2b3e9ojeqAL1R/4l1DyM849ethPTsmvWQJXGNs7EwGMyK1N2bNm8Nsk8N8B4zTAEuZRFItjgdtupJOzUjHYlhYxHndiu2DPevbyH6FwFZpwThjPCEfU9NImEuncvnWHUuPhuGSlnj7utGigOwYtwGisnJbV1m2phvPxyCLMwf78mZJamwX7onMyFWcD5bWt5ztgUNmMVw4qaiPInRQ+kVtF2d7o1rK1iBnAFO0sAzOaCEjUOHrW/5eq1LCEm8HpV4gv/OCW3gRh/9sIsA5ELl3DJ/uOHJl3yZuKNbKuUafb+QukdXF3RAXsXSv8ObfZMOOTjM7gznoLfZZPGkoGh5Re+lS2gBsTQHNWYXe6ijjob7yh7mVEXln4jb6BSnNT0mnoR9/PQmBRtK84cMmPxOmw+JHQOEMuZ5k3nxodC08gyNVOOG1UYgl6BDROpZX1uWRCB5uBm7Cs2iYCpg+J2dpzxXP0Gz/KNT6qcTTmIYMkeNBH+LwRLjQ6qWXQ4dS"
    }
  }
}
