nginx:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: "sprit2.thga.at"
    path: "/static/(.*)"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
  staticSitePVC: "spritstat-static"
  podSecurityContext:
    enabled: true
    fsGroup: 1001
