apiVersion: v2
name: sealed-secrets
description: Secrets Manager for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: ingress-nginx
  version: 4.4.0
  repository: https://kubernetes.github.io/ingress-nginx