apiVersion: v2
name: loki
description: Graphana Loki is a log aggregator that can be used to aggregate multiple log streams.
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: loki
  version: 3.5.0
  repository: https://grafana.github.io/helm-charts