apiVersion: v2
name: loki
description: Graphana Loki for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: loki
  version: 3.5.0
  repository: https://grafana.github.io/helm-charts