apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
  - host: sprit2.thga.at
    http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: spritstat
              port:
                number: 80