promtail:
  config:
    clients:
      - url: http://loki.default:3100/loki/api/v1/push
        tenant_id: 1
    snippets:
      extraScrapeConfigs: |
        # Add additional scrape for Spritstat logs
        - job_name: "spritstat"
          pipeline_stages:
            - match:
                selector: '{app="spritstat"}'
                stages:
                  - regex:
                      expression: ".*(?P<level>debug|DEBUG|info|INFO|error|ERROR|critical|CRITICAL).*"
                  - labels:
                      level:
