promtail:
  config:
    clients:
      - url: http://loki.default:3100/loki/api/v1/push
        tenant_id: 1
    snippets:
      extraScrapeConfigs: |
        - job_name: spritstat
          pipeline_stages:
            - match:
                selector: '{name="promtail"}'
                stages:
                # The regex stage parses out a level, timestamp, and component. At the end
                # of the stage, the values for level, timestamp, and component are only
                # set internally for the pipeline. Future stages can use these values and
                # decide what to do with them.
                - regex:
                    expression: '.*level=(?P<level>[a-zA-Z]+).*ts=(?P<timestamp>[T\d-:.Z]*).*component=(?P<component>[a-zA-Z]+)'
          
                # The labels stage takes the level and component entries from the previous
                # regex stage and promotes them to a label. For example, level=error may
                # be a label added by this stage.
                - labels:
                    level:
                    component:
          
                # Finally, the timestamp stage takes the timestamp extracted from the
                # regex stage and promotes it to be the new timestamp of the log entry,
                # parsing it as an RFC3339Nano-formatted value.
                - timestamp:
                    format: RFC3339Nano
                    source: timestamp