apiVersion: apps/v1
kind: Deployment
metadata:
  name: spritstat
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: spritstat
  template:
    metadata:
      labels:
        app: spritstat
    spec:
      containers:
      - image: ghcr.io/tgamauf/spritstat:latest
        name: spritstat
        ports:
        - containerPort: 80