argo-cd:
  server:
    extraArgs:
      - "--disable-auth"
      - "--insecure"
  dex:
    enabled: false
  ingress:
    enabled: true
    hosts:
      - localhost
      - annotations:
          kubernetes.io/ingress.class: nginx