nginx:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    #hostname: "sprit2.thga.at"
    path: "/static/(.*)"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
  staticSitePVC: "spritstat-static"
  podSecurityContext:
    enabled: true
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - spritstat
          topologyKey: "kubernetes.io/hostname"