{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "alertmanager-prometheus-stack-alertmanager",
    "namespace": "monitoring",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "alertmanager-prometheus-stack-alertmanager",
        "namespace": "monitoring",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "alertmanager.yaml": "AgBPf7J6XhEimCbkGy2j8q4v6cyhS22Yw4e9E+evZOqy9xLiN8QGBs0o17Wd06QU2Y4OClVTbD6qmYR/LphGv6umjSKJ83us7nL1CItiZQizj2JR9k6Dgno9d36MOKbfyBp66IORgFtHO6P7v+7MZts6sCVODGkh+0c6tJIMbaNNTbvLh0MB0mQRj+cdEpxtuQ+J7vNM08iEMzyAqbtFsk7NLN8ZFpJ24t0aXkrK2PcuhX4POThAvIxy+ojl0xTwwl3dbuqRU9XhgKuwMVTf4NVe1MYeB0IccdtV3iIOSLcFsRYoMpoi4dXDqaAn5V1Wq97AI0AIhslsbj1iSm64dOkQL7h18E/qVq3P7qfeqtvIMRzj8VcS922qOu+tOgIWekNwQqC3K5pYu4fOwun+hJjEwifwtrP1ZOCduYKkhEqDNwwEwWRgeFbKnJN+zEpk7KTmsxcbPOKYYDSjfHYVXcljcOI98k4/UHA8BgbnX54TZysGI7MgzkOXM23C+Qax2f2hBMo/bfMxMpNhvLvzGQTsVUYOzDNgJPuoqUbOMvvBrMUqHHi90HdfdvdTABt5x/1GmYwICCt+Ix6y07D0R5wwppLU35z92VGGQdBURZOEGK4CCL8Sn3KbRWg2RdduIZhGMnDrCtLffXQKV7nwck7QgGZUM6Z3cuDVc3o8I5eUCU86wtTbuGLaXHcmZEmGiu9ks6TtaCkq/En9Jju0e4xkjHyb9iUoVKDMCBHv7eo3HzpfbxwXyJ43yHQw1yPrCNaINIu8kxLg6jUWsud0uwrgB2zPgafeeqz8I0IrXSuz8/ShgG6iUSlmxzmoLKmMIFp+VCUswQrEs1IevFb4G6HnvVRb29gghIGElCU7uxFYy18w9ClP+HW5Wyi8xWUmMRhjfQarPyMHCKPXY1CjTjmj5Qk+d9M8IZl/I6sxoF+TqGGGgwnN/09Dy9u5SOwVRcbrahiqjYBs3rGcECz9ja2WDw6pg6gzdWTzV8d8TmGphKPhxTT9DGUUsmB05xEKEKj4GSxU6QlGC17Hzis5EHAljqnYGuJ4RfNR8GH53GsR3cspbXgeQCBZTE1VbV0w5qRxYSU7KWOKJb3WxV4FCZsYjGds2E+Gao8H085wfBCghpo9JT+BwRbnzRfgzc/KQx6fCfQrGOZ2AYYlcq98kv42Pe3TTQrus3r4xkotC8NoMlJY0ifqKTS+mr5j2+xcQNB9jXU6c46tF8KNL9iBWINRrQxrTOXL2gBIgTZWX9qlUTOUAQy0GTFMvZQEVywOxKEK5n2Fkck+Awj2rgTVPks3vIkKTlAcRTJsWGct8TNdffgBUGfD6I6wnv4shwpNXkY0YUZe1Wlf6pqj3dkvaOq0svqR2d0QhypswPH1YykCuaU1yppRzR+B53i3RduNFcQGMxxw/ztjg0jxv+Y4jgwd+CCBRwIy3mL54wA0KHSgojX4q04fb7j+KGUQRetvICNEGz/rMNVR2P7qV4PbhQaIA+rW+5bXbsNwsR7y67r+idU+PE16PW148PPKY2cbp7kipB/Y67kImHHvbBKI+biEXE/IbDjS8krqWZ1vIZxFfZKg3adXbhrdzdRvd71Eal97hB4gUg+5Ksy15ceQb6+IBiGEKnN2mBMtF08AHTBtiyA5MtJ/cC7NeoFO5gtNzAlRSly3olMrZzwk3JhIwtobK9QFPetrQyb3EI6EmQYgt04mQUDsiot0fNGeAR9I6xQQFUiuMw17qAeOxwGh6WCECPypxb3NYNq3iBUReEx1QNMFpevMmmoID67ZM25+qo3sngQ0gHbU83Bu2eLdOotr7f1j7g+ENGfceWorsYmwqq6ZMlnd/ACoX57cRWCknUgNWJYRLGiJ/J+2SUOk/i2pGj2rrGIxOiOKVCmWoAag0g7oSI3LVFMc3cBdEtMgq10rtPponBA9ctnIjpv96/DnEw0ZTepnzud/ATwA0ZRw1JFogWR7Sc8X1Wy0NYyAx0ZnahKu6LcYoDutecGSbYMVcW+v83CJK8lLWmLNHS/UaUu7g8s1AMsRg/uVHtu4M4r+ihZJaw5nqmV0fHrNaqKHCSyYvZdO8rIJmQYCOsMdAORfXslZksfEInmTpq4k+FFiwXm+kh8tLMguSrcKa+unEXfJORVB9orRmMxm1sgnRHBLgxQXpr0="
    }
  }
}
