{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "alertmanager-prometheus-stack-alertmanager",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "alertmanager-prometheus-stack-alertmanager",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "alertmanager.yaml": "AgAXX+mWmlRPK+G9FCf0diEM/L+X1LRcJPRkYLNIzfCCiLXv6YJgUEcdn23xJ8XaYRI72W+ou929TrzUxDoX+f1TuOIzfOOAbWP2Eds+xAq9EeoBR1bcLovyBc1eTkezFoDNVCaYnw/s7sOs6+cQdrXiz4+jowK8/NVfPCrAiVkHRZJ7mQW9OGvxpTmLeZNCNw1R7XFpDcq6qR5ZyEZo8MoKa/OCPMVNxwXFPEU+p1SS/bch+lNSB7TkuXKfHBFJkW6FrRnYV9A0iZW77udIo0Yw4r+l68wHPKsCX4DlYvHLJBseLTi0GrKIOT4CgAfmTsl659fj3+jQxMP8v9qCIQKhqlmNMNMKQ9HCxCHFPNUNzRQHeTn1nLk8ENWOpDZHN2Px/gnl+udETl3Xqyy//YCeiQoOSFReH3y1rOQM4aETLsZy3n5I9hazZtQKQn1YILYHmmeg2Jb1lNsIp+5YxjCZpUQfnm0PgMw9ABGNJA/FasI81246t/EorsZATGdZ73FOt+gBTwftrN6FDgH2hzByp5m+6r1Xo58wp/zLdApc0gCKF2bQvGr4eoqV81iX4tcTipak/vHgXJ+QwcWADk3SEMA5LpxfsXgKo8pzgqJdq3wxL9LJdhuDl+3DhRcCqxF25rt+rI4XskvG04wKNHpJkJdbloZibwNQftT5brTyGD6LTmiR3M+KIspo9Ku0LdVu45qDJZUHSGuKBOKsAvLzH/uy0fXX9eFRbh0XuOMMTwKPIodfyhgNILSZs684ssdIXvtuCsNm17RVPpUPDrirgqZdRe5wSXk0ksciTEnDZXe2qzSm1I59pwv3MVVsFID15BHCwakr1Q/H/Dg68xzkTuR19rjauZQERnUtbgEbrivhRJzPpxOYjZBIFSlU0WtKVczE1clkD7TWMB53H+YRBXmxs4uxkwr7zNx//EKrvIUbNNQrJgpj2RyZBicS/rvTbIQXqq4B7q4BDnyx2eJKg8WfVwiDiB+20VK9ZWHEJQmLx1eau6l5FA+33Q/WE0ileHqy82dyApe3y0ORXvW0suEY2EUc/n4oIE94hpM3hTmoT61wo1m3MhaJsWRBOyfkWHpimjOObKveV37T3oOuWUR4SjA8veSt+1zff7B04AoI+fnXfyAZgAEOYfVMI6rpO6ef4pE35ctmSFO4IoIwn2QsYbUc7wHyPuLqmkgmVHXLZnn6Pz7TUbg8cbHZMQD2P65PqUFnEQ/mOZcRYDAW+SlWKeXO6rE6FqRYp8ZSHKzGLWZE+wBMSer/A7DixIGrIGvvad+BSgWqcSJfxhNJ4+kP2u4tF8bz2u9+csrvpS9Fy1dY4Q6DwTfB5X/f63YUx/lO0HlT3QKHR19DccfL33ClmN/7Ksx65etHxYwFzF0BRYy2w4lyxwVedxsO7w6+sRK1xr2W+rVAKYTu/uZ6E6lPjjBL1RiXY5l+fG8Zt4yIwwPO6/Sp9HYppqEpNUbqu/30caMGXn2Pv6EbLClLDAz20vYf3a9xYw45q2U7sSphmrxVpRSIiSu/X245dTPn9WdKNmdEtu1eG3m3dLYydQwziPfQt+kSnhrGaV9G+N1KGKyv6tmPaUW+sSCh0/5C78r+HgLuV9eIeYNY9LtI8yWXz4iKWjHp2BvWGND3k/74o+MvPTV7VGCpcq80IoSIoOnNa3IEfeEuS+2I6SF/KDPY7pI+YAABVQ+l29qaGBjRO1cyBtGXRtZynpv2Q4ZTCvX2oSOKdjKYqWiijlozxtqxLOSXklQzHd9DtqDPZOlamxZPSdeUXWJJMQgH6jFNeAYkMYj2/xQED6R5SUMVp6JAk0lcW5j87/eToSRjtCm0+kFiTkZC/7qzRXxCpGzASTU50KsYV/Q5evg+VCxjDFwa3PdIvKfbW5wz3tOLHxrJ0vrqYDEv7uPgoW4M//VcdOiX3GFgLhgMGHq5AI3+C6JKjuTpofoFFyBeNFuAEQxbu0MU91RVI+4nmqUZv3qlor2nyk/7kkUiAQGlD5QMg8TsN4qlT+Fe049T566ZOu7+wNe8bHxkrVE4FIwjBe+eKoG9qFdIH4mqIIdl+reNHPT9UlEM1ldKZhrktZZH9iww33xM1ZK0n+1Ehk8pEYJdWQuc7GlEjCCp/3g="
    }
  }
}
