{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "grafana-secrets",
    "namespace": "monitoring",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "grafana-secrets",
        "namespace": "monitoring",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "admin-password": "AgACupCqHKbDESiwBfvkBiMQpj/ZykrCuE5HVZ2leFAO6cDWC5wXegYLRnSLKyMADhnmlLMHFIo9K2Dyan//cNpze5AYdNKuRDgZ3YdrJEbhl9CfXgx6p2SLYQsaXd6+tPWynJWnrEdfQ8dcE1Y609dE2De+9DKezPeV81s2xwXsFeItJHWVjxS6lautTDI8HKQvG+qIahj/I4KTwVSo1LxRcw7qlCR7txyDsvgNTcbBRwQm1HfETJyaG1pHecP0KzjMWfKBAnRQCc+UBlHPDhyxEjzf5Scq9kY3ddMG6GLC/I3UX6lT5J/UZmpuu2B+szqbhp4Ppp8QeaYWaHjLbU1Bg0u94oGzze0Hi8Y36U34wXkQTMI7oUW0izkGXR7O/fh+0LgaEVbiaITrJWofBc/rrBiZl9Q+Rxukq0iSoBUkaD+T0Atb6sgCOwdbWx2Z4h5QDqiUDySDQ85RcUYyim39WlneyymcR5seDcQ8I0DUTuemtLOhrTIkUgFQq9DrSyVUj5S5dlRKGcSBNYVdGe0vKpeZFQaf3vbxsqiv0aSxSDjJ64kzjxy8bNkPcVU4Z54VdRYcfn7ozSRxXTJRuuZD253UcqnerUDIESiHH++JWugi3LfTrwcIX/AInTst3a4E0VD3pwnNMQYxqxLqvb2Xz9ay4jkp+y9m4OrxwOrf/x1ZMYhG20ElFMKbcIY4ezlkh5P+pQ==",
      "admin-user": "AgBWQmL/iU8fxRLVvqEBRf/84O0l4Gokc+GLQtfIwErvjUKzsBQptkjVMdkk8frcPFyx779z5FHGSyhXEaHPrKg3yRclgimrwqdaqDpHlDpn/tODRanfzSr+OYieNcRMbKhrfs/36g9wh8OldFd/1Atetxo9BQLPVkQWz2WYcyLYXrVfMtO4DURH7nX0DvSS9Oneg7UaYBb/O8Q+C2Oz8W6h/rfRuP2E/HWWjg93CIBjEoVFYW+KQ4wk32ClwZoElM8lspTiTTal67VKkNqH7k4D+2vRnziBGdw2CgW0e+GmG5q0HKZ2GTPFo0HOEZk0+Q8x96SYFg7PPWCbCS1spH1ydGC2Iu7IBMbFIj+x6L1PH4bBBRYOI06hY7Yi/65Zg82Udc+GDwaMVCSdDAkr+NraatSFXazjXhCLBZxYl4lHNOHCY6xsowDxkStez2GCjlLJc7Rt9umqIIqWX7ZbiqZEUMUcGGWNyJK33xRqjOiiDcjEhMPiBLRjl+7qLPcj68xIlYVAfmbNuca9yVrrAnFnyd253/xEg+q1RFN2gGRQYy5k9groT4ahZ6XaLGI2IpWfyTcZWteEHz61dAC1Vzd0+Oj9S21qQTgaP00L+JZ1SRWxoVCTYXZ3Twg10ZG8C3t/GwGiPONV2UC0IfQNcmN+wlMnEZA9sj1RWxR+3pXk33LwipiM56QgH+Dh6KiBt/9JlHSY9A=="
    }
  }
}
