kube-prometheus-stack:
  grafana:
    admin:
      existingSecret: "grafana-secrets"
    smtp:
      existingSecret: "grafana-secrets"
    additionalDataSources:
    - access: proxy
      isDefault: false
      name: Loki
      type: loki
      url: http://loki.default:3100
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        loki:
          gnetId: 13639
          revision: 2
          datasource:
            - name: DS_LOKI
              value: Loki
  nameOverride: prometheus-stack
#  additionalPrometheusRulesMap:
#    spritstat-alert:
  additionalPrometheusRules:
    - name: loki-alert
      groups:
        - name: spritstat
          rules:
            - alert: spritstat_errors
              expr: sum(increase(promtail_custom_spritstat_errors[15m])) > 2
              for: 30m
              annotations:
                message: 'total spritstat error count ({{ $value }}).'
  prometheus:
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: 'blackbox-external-spritstat'
          metrics_path: /probe
          params:
            module: [http_2xx]
          static_configs:
            - targets:
              - https://sprit2.thga.at
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: blackbox-exporter-prometheus-blackbox-exporter.default:9115
  alertmanager:
    enabled: true
    alertmanagerSpec:
      useExistingSecret: true
      configSecret: alertmanager-prometheus-stack-alertmanager