{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "alertmanager-prometeus-stack-alertmanager",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "alertmanager-prometeus-stack-alertmanager",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "alertmanager.yaml": "AgBIt9FZuz4e2jaRSkg++G+y8xlEaf/GMsYUg/AUZgHzBbmYdOvzm/QgVtR3VHvCwiqjzM5dwFxgdY/7gHIh6CfcAmFdE4lmzrLzOuAyQcG5mUs1iiw2vHcOIRZ5JUQ6WZmqjm5zNqlX/bGMC8O1MiSLfmb9yCDFQ/AIS+m8MX1dpco3tJ/ibk6CobIfOHjxaGZYdER7wXvfGxylmplnncZvOZ7v7Zqd6JhBX4Hf6E6GviHKV0rWTO0xkUGa3HLzAd1i1RSmByQognK1KPWqL1zKnx98Xkw4QRp+qsTXnhQ77vmxt2rZjEKrnQsQrW7vG8k6oaDN/XcnzmdZN8YrnT4bWjJGi5viGM7Td5GieXM6efi0FO/D3w6bLhM0z4uO0oVqru+9hvFlMP7oUBwGWsulBV0zM2nYbLD+t7naON6iLYdiGTqvRYmje8LFKWrTP9UnMirhWpEbtZovn9gaS84Khu/kC/tGZfUtUTQW4HBQkQJM4AE5YkOlFNI/eMar0DreRRVJc63HkH7eE7WTJBWJwzWF99s2JwqaS96mpavCXyohBYNfY/M9CoIejXlLk9URbYye34y7iabFiU9VJOad/Z3y/uoCix43FHVAFA9D2HlZWGYG5fZNXmY6NvmO2mA20seUgEaeWncZtuI3DkJp8tCtHS7n1C3dlVy7s4nnd5lBw9S8t0z9Quj8HvHRiiqrMkFBo8jxMM1vGMFGMJuZNU+eehD5sulNJ7io4tRAE8KiJx6s/GgCNYYElkKWiW4ALgr3F4nC6WMU0Qf+NoKwHyPpeJytRcArlwT0A3t+MlKXHsnJvf7HwknirlzOHFPQcGi2hYIG+EEDgDl3zJ3WCkx5KGl5ydMjiSqNQJu0C+qB1rlInLH3hQQha6oPXCX16OgJGeNqWVB601OvZnmEkaR6HLtP+Cqhqeaq5oootltaPTTXqr+Eb9hErxeIKY1zF9qVin/KuTJHrkt0oW+/1QycnUmr8OGY+Ir3rk4yuOoq0WQW93zUsTJarWi8A3+ZJJe4/zCZGpr+iMd3HFDAtpYVlvWKrW1cex90qJthqVIDb0ZBQuYivPmJhpecLIzej9KeE4TJxIZ9pwaT9wKX3bJBbmKtZvpMazJJDaiiTOsKZSAX5waIb+IxGb3aR9R8Eu0OV0JkiBDB4t7abUwdQVojtKfMIu9F3H8Ff5hYj8imUv2XJ9Me0J9Zs6AC6EwfAY6zQJlN9XcFJ22wkYDjWs1kTXS/7nZLY95Tb9GBCOMtyTUy1mQhvZWC5RiyGUGwpVMZIQb6iHZJzStZQGsUgkoU7UM2wx6ii+Y7m2TS5vL51NZr5lN2KrJJIbIWDDiBGl3K1tHJagudQh8+3+jmBo+up8cEHgP+vEplCeGxY+oQzs4oSBMu6u/pHrRScuuoZELgjVx0Pg3sQL/tQqRQQXXx99JMJol0khuY3sDEnFinshfLONuKbe+AvwIVtDfCPWYNqSNtm68P9jvqXuLo/lsEy50SWSsKKpAjWRcizoPviVIv89PQLXox3FB7Zd2jVaFhF8hF3QJ7ueImujcRR6KfCvt7R1ONtx91pVXRLs0/NrMd2BQPxgwXFeeugpmnL/60rslKZ7MRYhfpRs35GZ552Bf5fYNgbdOvnX6bMoslVOQpyBeFGrk+YCfy97PAPDp92dWYVRY6xLE78ZVEZtDKq96wwmop3GWb3u7L1PVLNvNGf42+0d4="
    }
  }
}
