{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "alertmanager-ps-prometeus-stack-alertmanager",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "alertmanager-ps-prometeus-stack-alertmanager",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "alertmanager.yaml": "AgAiQZ5My3DFWDjk7pyBsrByVFiiog2HqT9IC5ma7DaTLwd81aCQfAVHa92uoZ6Xxk69vikjbIUUFlxABP9Wa6CdirgZ4c+/FTIn6fQm+hXbhwu/BCNiz4LpLoCmbDXlgUn3krXfqJT465TFZ0IdKRr46tn7BCsMTmObMFQXo8okv6eFEBOpyHCdYByZ2kmqB2x4nNyRDs1OGI++9HorlzqMYd481weMW13lguiX+HaU2UJiOCMULUwESLQe2f28N50y9oaxBZbNeezQd31rQ8dul3oV8F6cbrVEjKCRTOeeVI6Ixy/N3W39GTNwbcODfnd4v0QRoW0vdcsR4DMEJfo/Bjyolt5u7ceTJivO1Y1+kWXxm/OAa17h7Xn3PzzfNxUppqqdt+caRxK4q+2gu8ELpKpIZpUL5ptOCzHAGEJLcUwn8LD2Zzp35CIrIAr7zJkUTOvikio51cqSPEEM0A5jp8fsQ8GyCVpzpWQw7UNaggFk4wlDCrtCaeIEdKtDMiVghmVAXySZvlnf+F6q2THxgIUXXkyrCLbSSJ5G/Le6U1xm+Fdin30Kp/txzG4UxVbw90BUTOfHkiPHOrnw7fmTeVqgY5ZfLm9CTFVxO0wGfARAdbwmwbHySI3lmNQyoJR/pD7bbwH2zRyAUwYz02Rfq5A5wbHJ/bencJ63wHaZpRUshf6ePoCnQxI90aL0n+TOI1LUg4TK0zVXbeMZqs6hrSwHLsZdjRO3gdsUO7H6NCjY+ghRIHouqnI089/UdETk+I2uSx1JR84+HNf5m4yclLfMlOfYTT9RjEmXxlR8XvSJZA7UGgqTGfSGOD19U6YyQ2I6ch2Cg6dZFdCVFA/qVGVJUBKdOaMFieijyprflYMyfUsHNdmgyti2//Tedo9qTE7ktP1f/1xjJL1/cBU39i54EL4snD2Y8nCyteRRa4Y00lgL+ljRM+lLVTXeQj/rWYokpwQNCsI7oqQrIqvRTWKj2BAklIlC9dJSPM/IneyRKeOi+hwOPkM3ldxpSeV9+T9H7RVWenhXLkBa2qnLrKEnkmbL7FdGUxGakCyvt81300M3MJmFdqxYX8zLlAwZ5Uy/qYT5YXCMklbOia+KFQMex8pMDCv9IgjJSIgNUe8vVgphsddQr9OxJ/Q5lLiJWB7HDQNPuBadEIgF6TveAW+33tp8y8t93+1+IRJRzGYha+GBg51mC6El9qZ9oaJ6jQShd1PE/xotzmB5cHiwTDKGp+UuTHY5DZeTkefNmGOaC1e843KGmhkTVQ3d4OnwhxkaBOEwUNYSRhhQPxMGl/IFnXpzo+XqGZOGQEaUJkjmVUYykBV948Ag2qriEFAzsXDls7jy0pbK7LMfdQ09nF74D/ThRqKsCe1wPkJJ3cnboz/2HRZE9poZ2UJX3PBfDAjtM7q/pxeBispyOi6N8PfNxTF+dNBB1O3KoBYw/9Nxjs9wuIbLe1hjhH01qE/wg1MlMGtH6uIPoAGPutvawZk60/Mgp0pv+bfT0Da9fnPWTiTrQ0viqO3YeQ=="
    }
  }
}
