{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "alertmanager-prometeus-stack-alertmanager",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "alertmanager-prometeus-stack-alertmanager",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "alertmanager.yaml": "AgAAE1Flq7FnPsXYztUa0v/08ALbCOusmHDrKLU82yhImYo7ZhulIWilqEGvFzGfrNmK6nGvtkz8yKDz9jHPED0wnum4mRAO5mdoLS+myIq4htv6U2ggEjkvjumg/8P8wTEkuylQsMgzEbhfXDc8VyOyphOMt4le1NITEQfjcVB2wU7wARuGsT/PUL9qBdao2z/8NPQSO68wpdQdV9HVrHhhC9SltYA6UpylhjqoCis0lDbkvNWSiCpRvqPY2rgXUv3SRGsyYuRkLxAN1/iPEJ1AQWkzToFlOLlMIeE8ptTyHFE/xsYodcLyKtx/hCKBTmsLjYfNd38awl31mjDIlOoLEVz7u1xfj+G9PDYW/dV+VNZL6UfetP3Q1W4M+dnIYf/zQ1sPZvZumEkzDz1/UrBdQeelD49zv4SQRCJlF1WVrFp3G7jkXgwPJjPxi+Iq6k786c3CgX/18ElTuuG7J6Las0e7y0UegCP8TwRVog+DNz+2lxggKhs+2OpKumK/KdAsibP9pbdCuvq8qX3QjkzqXBcMLG5EivFe8fjNWWDzpnyQvy4sXQtDc5nqn8ByagsFalPjMEmmvFmmVFDuzK0tRfTBq/JxmeVWsX+wDTEESghnocG2fZkBhYK3L8BAG56tFnH1nznEH7BnokXVqE+GAFqanU9CaCaWSf4Yf/G8EK129MalOmJh0L+R67kHyxJHJLZz0mzKrQ95LDHutFfTDGgS6hI2789Zq6OLcp+vyY+r0MoqBWA5+64CIbAORQmimxru/7Ksbsd62N6yt94YzYRuWyQueDpcu4i34iy6Jolqw26XC2tu+rCzCSBeCRPnXyfQaykQWGmctiHClLpH5w2e+/r/Y8sNxRs7e/3pRNrgkkG1TvqK4QhBkDZXW8q9c7Tc2RusgYPqN5B1TN5Wr90kWIIJWgPkULTuNwdgnpXJ/iAnBriTBiqvFAiZIrQStVCu0EBgBrszloUzBTVrsUGl1G4zA0ydmnFw1Q6+Tul9wYO615imNa1thGaMYEHYV2zHAkXrFEiDeIVmZf7b5wnlSIksMJPm5BkG5rVhdmthcSssi56hz9lNxdIw6vUq7rN4B9fYt2jCtFTsybkxwlJQBFTaP35VCmN7KLnklWdv4G+cXzIYiTkZqpz8n4c2Yop/YqtrIfDIplrjbWcRip1IMcDZonkuiWyW7ZLNSIacDDZoQcfWqeZRkVjii1I6CUiAJ7eI6yuW9PgGX/jO3VCUb4Mg7X/lNEipYTm3rQpi46Ps0KlTM3XC7TOPlaBENwXV+I68/YLcClzruBRX6d79pCf2Sef2pfOcHAvM5u8sjnVllBbGCMnQ6y6b4R5+Pp0cs5oGZ9/0Ii7GqCsS2plWWPU3DvOQMptWyIO80zS0T2oTq0S9kb3tjX/xSnrxrII13m0i0p9ICXyChr2xNdAl4NvXPBupJ+LZkLyg/wxobYur//mwfwvmCcjZU8X3HXq4atgKWPRQXF4gWtDFK+MQcNdpZuY9A894jto0xvTmZ11gdi0X8VTVpp7ElkqsZ34VY/FhFMZQF5W81CUI67wnlH28TlW1IuSEDYA1ymiIf6Ypgd+RhNyAZqm2v7s9gejw8mzJ+h8a8ujas2luPsD3zuJSUgEkY/DnLZW3Df9zm+l3F6rRimTXqdiG2OkAJOhyAu6bRSU3aUDDtueeKkXC+KN/RoYME0h2pt4DqQura4MCNuJZH+DTou+fnVs885vrjG8Ow1O1BtLRwqifxIrRGfUXUqL8j4H6oHEZ18jWF/2MC2fZ"
    }
  }
}
